### ISSUE TITLE
[O] Herokuにデプロイして正常な動作を確認する 8F

### ISSUE THREAD

**Issue by umahara555** [umahara555/enpit2019_er#5]

**Comment by HALtitor** [comment]
test

**Comment by Soto-soto** [comment]
Herokuは1コンテナしか動かないので
submoduleを使用して，Herokuを2つ立ち上げてフロントエンドとバックエンドを分ける

**Comment by hogehiga** [comment]
こんにちは。
Dockerよくわからんのですが、dbは<https://elements.heroku.com/addons/heroku-postgresql>を使えば、立ち上げるコンテナが一つになると思んですが。
適当なんで違ってたらすみません。

**Comment by Soto-soto** [comment]
APIサーバーとフロントエンドそれぞれをコンテナに立てる予定なのでコンテナは2つ必要になる形になります．

**Comment by Soto-soto** [comment]
ちなみにAPIはRails(APIモード)とフロントはreactで構築する予定です．

**Comment by hogehiga** [comment]
了解です。

**Comment by Soto-soto** [comment]
herokuでコンテナを二つ動かすこと自体はできるっぽいけど，それぞれのコンテナのポートフォワードができないっぽい
heroku内部のポートの指定が自動なのが原因っぽい
