### ISSUE TITLE
[F] 付箋を追加出来るようにする 3F

### ISSUE THREAD

**Issue by umahara555** [umahara555/enpit2019_er#9]

**Comment by umahara555** [comment]
warningでた
```
Warning: Each child in a list should have a unique "key" prop.
```

**Comment by umahara555** [comment]
> warningでた
> 
> ```
> Warning: Each child in a list should have a unique "key" prop.
> ```

とりあえず，下の感じでいけた

```
 <Card key={cards.length}/>
```

**Comment by hogehiga** [comment]
どうも。

ここ→<https://ja.reactjs.org/docs/lists-and-keys.html#keys>にkeyとしてindexを使う際に発生する不都合について書かれてます。
そのうちあぴと連携取れると思うのでidあたりにしておくと嬉しいと思われ。
